### PR TITLE
Add Elemental to the header/more from SUSE menu.

### PR DESCRIPTION
**Pull request by jhkrug**

### CODE REVIEW

**Review by andreas-kupries — DISMISSED** [review]
And kubewarden removed.

**Comment by jhkrug** [comment]
In particular KW went back into the menu as a decision coming from Guna and Mike Latimer. There is likely to be more iterations on this with inputs from various stakeholders over time.

**Comment by jhkrug** [comment]
> Yes, there are also k3s a Longhorn, that are fairly popular. Not sure how many projects we should have, and which.
> 
> I would try to order them by popularity, like:
> 
>     * Rancher
> 
>     * Rancher Desktop
> 
>     * K3s
> 
>     * Longhorn / Kubewarden (CNCF projects)
> 
>     * Fleet (not stable?) / Elemental / Harvester
> 
>     * Opni (not stable?)

That ordering is being laid out for us at the moment. Consistency across all sites probably.

**Comment by jhkrug** [comment]
Probably, there will be a reduction in the number of menu items in 'More from SUSE' as well. Discussions apparently ongoing. But, in the interim, I think this is fine to merge.

**Review by andreas-kupries — APPROVED** [review]

**Pull request merged**
