### PR TITLE
Install Epinio on EKS

### PR DESCRIPTION
**Pull request by riqueps**
Epinio installation on EKS does not exist yet.
Just create the first version.
Following the instructions you'll be able to get Epinio completely running on EKS with an ALB and WAF in front of it.

### CODE REVIEW

**Review by gitricko — COMMENTED** [review]
Looks good, but where is the WAF instructions ? If it is standard stuff, then just put a link to how WAF link to ALB

**Comment by riqueps** [comment]
> Looks good, but where is the WAF instructions ? If it is standard stuff, then just put a link to how WAF link to ALB

I put just the main instructions to get Epinio running on EKS.

WAF and Certificate creation/setup were not inserted, but if it is important I can insert these steps too.

**Comment by gitricko** [comment]
Lets put it all in... but we can mention it is optional

**Comment by jimmykarily** [comment]
Thanks @riqueps and @gitricko for this PR, it looks great to me! @nunix can you have a look too?

**Comment by riqueps** [comment]
Thanks @jimmykarily.

As suggested by @gitricko  to create WAF (web acl), just follow these instructions: [Creating a web ACL](https://docs.aws.amazon.com/waf/latest/developerguide/web-acl-creating.html) and to request a AWS certificate, follow these one: [Requesting a public certificate](https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-public.html)

**Comment by jimmykarily** [comment]
> Thanks @jimmykarily.
> 
> As suggested by @gitricko to create WAF (web acl), just follow these instructions: [Creating a web ACL](https://docs.aws.amazon.com/waf/latest/developerguide/web-acl-creating.html) and to request a AWS certificate, follow these one: [Requesting a public certificate](https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-public.html)

Hm I don't see these links in this PR anywhere. Maybe it's a good idea to put them in?

**Comment by riqueps** [comment]
> > Thanks @jimmykarily.
> > As suggested by @gitricko to create WAF (web acl), just follow these instructions: [Creating a web ACL](https://docs.aws.amazon.com/waf/latest/developerguide/web-acl-creating.html) and to request a AWS certificate, follow these one: [Requesting a public certificate](https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-public.html)
> 
> Hm I don't see these links in this PR anywhere. Maybe it's a good idea to put them in?

I just put the link into the documentation.

**Review by jimmykarily — APPROVED** [review]

**Review by nunix — APPROVED** [review]
Approved as "v1" of the how-to. Another version with more details will be written in the coming weeks.

**Comment by riqueps** [comment]
@jimmykarily, does this how-to will be available at [
Install Epinio on Public Clouds](https://docs.epinio.io/howtos/install_epinio_on_public_cloud)?

**Comment by nunix** [comment]
@riqueps hi, I'll add a link to the EKS page (https://docs.epinio.io/next/howtos/install_epinio_on_eks).
The public clouds page will either be removed for single pages, as the one you created, or totally redone.

Thanks again for your contribution, really appreciated.

**Pull request merged**
